#Show content warning on launch (Disables automatically)
showContentWarning = false
#Enable/disable the gooey inventory
useGooeyInventory = true
#Enable/disable the gooey hearts
useGoopyHearts = true
#Enable/disable compatible models to blink intermittently
useBlinkingEyes = false
#Caching generated latex covering textures will decrease load time, but will disable recreating the cache if you change resource packs. This cache is stored on your disk. It's recommended to enable this while loading large modpacks
cacheGeneratedTextures = true
#While generating textures, the generator will store all used block textures in memory until all textures are generated. It's recommended to disable this while loading large modpacks
memCacheBaseImages = true
#Large modpacks will eat up all your memory if unique textures are generated for every block, this will apply a generic texture for all cube like models
generateUniqueTexturesForAllBlocks = true
#Got a lot of mods? Unique model generation will be limited to minecraft and changed
fastAndCheapLatexBlocks = false
#Specify the location of the transfur meter
#Allowed Values: BOTTOM_LEFT, HOTBAR_LEFT, HOTBAR_RIGHT
transfurMeterPosition = "BOTTOM_LEFT"
#Disable this to test fix for black drip particles (https://github.com/LtxProgrammer/Changed-Minecraft-Mod/issues/1291)
renderDripParticlesWithNormal = true

